### ISSUE TITLE
It doesn't fit in my screen - Scrolling bar...

### ISSUE THREAD

**Issue by LinUwUxCat** [Luca1991/NDSFactory#2]
Hi, The app doesn't fit in my screen... ^^
Is it possible to add a scroll bar? thanks!

Version : Release linux - OS : Ubuntu 20.04

**Comment by Luca1991** [comment]
Yes, I'd like to replace these QLineEdit with something better (like QListView maybe).
Expect an update during August.

Thanks,
Luca

**Comment by LinUwUxCat** [comment]
thank you!

**Comment by Luca1991** [comment]
@L-i-n-u-x-C-a-t this should be fixed with my latest commit. Can you give it a try? Thanks

**Comment by LinUwUxCat** [comment]
Sadly, it doesn't. I still see the exact same things, without a scroll bar. I cant reduce the window to make one appear either.

**Comment by Luca1991** [comment]
@L-i-n-u-x-C-a-t I still haven't implemented the QListView, but in my latest commit I fixed a theme issue that I was pretty sure it was at least part of the problem.
Can you upload a screenshot of your issue? if you go in the about window, what revision is displayed there?

Thank you very much for your help!

**Comment by LinUwUxCat** [comment]
Here's a screenshot. I can't see the "extract everything" and "decode FAT contents" ![image](https://user-images.githubusercontent.com/46047705/110622197-6e936700-819b-11eb-9193-de8a29a087b8.png)
I know they're here because i can see them on the windows overview : 
![image](https://user-images.githubusercontent.com/46047705/110622473-caf68680-819b-11eb-8914-c38634215001.png)
EDIT :  the revision is f64b070

**Comment by Luca1991** [comment]
Hey, just a quick update:
I finally started to remove all these QLineEdit with more user-friendly QTableView. So far I have completed the unpacker tab, but the patch isn't merged in master yet (I'm currently using the ui-qtableview branch).
I'll merge the branch once i'll comple the QTableView in packer tab too.
Here is a preview:

![image](https://user-images.githubusercontent.com/3731220/111354600-c7289f80-8686-11eb-8a12-e1d701ddcdbb.png)

Please be patient for another couple of days.

**Comment by Luca1991** [comment]
FINALLY the branch is merged in master.
You should now be able to use NDSFactory without problem.
Please wait a couple of mins (building time) and it will be ready to download.

A lot of changes were made, so please be aware that there might be new bugs. Just try and let me know.

Thank you for your paticence.

**Comment by LinUwUxCat** [comment]
It works, thank you very much! "extract everything" produces an error, tho, but that's another issue i guess. closing this one, thanks again!

**Comment by Luca1991** [comment]
Can you please open another issue with the details? Thanks a lot
